default:
  image: ${DOCKER_HUB_CONTAINER_REGISTRY}/library/golang:1.26
  cache:
    key: go-modules
    paths:
      - $GOPATH/pkg/mod

stages:
  - lint
  - test
  - build

lint:
  stage: lint
  before_script:
    - apt update
    - apt install just
  script:
    - just lint

test:
  stage: test
  before_script:
    - apt update
    - apt install just
  script:
    - just test

build:
  stage: build
  before_script:
    - apt update
    - apt install just
  script:
    - just build
